### PR TITLE
Describe new simplified labeling conventions

### PR DESCRIPTION
**Pull request by plocket**
Also, moved more complex stuff into an 'Advanced' section and some other stuff.

### CODE REVIEW

**Comment by plocket** [comment]
From @michaelhofrichterHVL in Slack:
> For `plaintiff__2` do I use `plaintiff__2_age`? And then if I have to use it in two places, it would be `plaintiff__2_age__2`?

My reply:
> That is such an excellent point! We definitely need to add an example like that! Just so the knowledge doesn’t get lost - it would be `plaintiff_age__2`. I’m not sure how to describe that in words. It’s the field name as it appeared the first time, plus `__n`, with a unique number. I’ll make that example change right off, though a clear description might take longer.

**Comment by maevemacglinchey** [comment]
Re: court information at the adding form fields stage, we should stress that you must only include this where the user would have access to things such as an existing docket number. For example, where it says 'docket number' (for court use only), we shouldn't have a field.

**Comment by plocket** [comment]
> ... where it says 'docket number' (for court use only), we shouldn't have a field.

This document might be a really good place for this. Another really good place for this is in the field-making documentation.

[Edit:  Not just about docket numbers, but about 'for court use only' in general]

Thanks!

**Comment by plocket** [comment]
From @michaelhofrichterHVL in Slack:
> Should `incident_4_digit_year` instead be `incident_date_4_digit_year`? And the same for the 2 digit year?

My reply:
> I was worried `incident_date_4_digit_year` would be too long. I was using `_date_` to try to be imply that things with date would be numbers, not words, [and I thought "4-digit" was already explicit], but you might be right that that’s not explicit enough and it’s generally better to choose clarity over brevity. Let me know what you think.

**Comment by plocket** [comment]
From @michaelhofrichterHVL in Slack:
> I haven't looked at the forms much at all, but am familiar with some of the same from Texas. Do any ask for the ___ day of _____, 2020? Meaning they don't want `10` for the day of the month, but `10th`? I know DA can handle that easily, but we'd have to code for it.

My reply:
> nth (like 10th) is a thing I didn’t consider, even though I’d considered your #3. I’ve been debating how much labelers can absorb. Maybe the dates section can act as a reference section, though - just something to check when you come across a situation that you’re not familiar with. I should put that somewhere. So then the question is what name to use. `x_date_day_th`? I hope something like `3rd` would be understood to be included in that, but I don’t know.

**Comment by plocket** [comment]
From @michaelhofrichterHVL in Slack:
> Is `incident_date_month` equivalent to `March` or `3`?

My reply:
> I also wasn’t sure how to do this. Again, I had hoped that date implied numbers, but maybe that’s not effective. For name, maybe `x_date_name_month`? To that end, should numbered date conventions be `x_date_number_month` and `x_date_number_day_month`? Should the rule for `March 3rd` be `x_date_name_month_number_day`? Maybe the whole rule needs to be more formulaic, even though it makes it long: `x_date_name_month_nth_day_4_digit_year`, `x_date_number_day_number_month_2_digit_year`? Thoughts?

**Pull request merged**
